version: '2'
services:

  proxy:
    build: .
    ports:
      - 8080:80
      - 8081:8000
    volumes:
      - ./configurations/nginx/conf.d:/etc/nginx/conf.d
      - ./configurations/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configurations/nginx/logs:/etc/nginx/logs
